#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

#setbg &			# set the background with the `setbg` script
mpd &			# music player daemon-you might prefer it as a service though
remaps &		# run the remaps script, switching caps/esc and more; check it for more info
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &	# Uncomment to use Xresources colors/settings on startup
xcompmgr &		# xcompmgr for transparency
dunst &			# dunst for notifications
xset r rate 300 50 &	# Speed xrate up
unclutter &		# Remove mouse when idle

# If using a virtual machine use these settings
#xrandr --output Virtual-1 --mode 1440x900 &

# If using laptop use these settings
#xrandr --output eDP-1 --mode 1280x720 --brightness 1.3 --gamma 0.5:1.0:1.0 &

# If using 3x monitor use these settings
#xrandr --output "DP-1-1" --mode 1280x720 --left-of "DP-1-2" --output "DP-1-2" --mode 1280x720 --output "DP-1-3" --mode 1280x720 --right-of "DP-1-2" &

# Keep an existing nitrogen setup;
#nitrogen --restore &

# Radomly generate a wallpaper in nitrogen from folder every login
nitrogen --set-zoom-fill --random ~/.local/share/wallpapers/ultra-wide --save &

# This line autostarts an instance of Pulseaudio that does not exit on idle.
# This is "necessary" on Artix due to a current bug between PA and
# Chromium-based browsers where they fail to start PA and use dummy output.
pidof -s runit &&
	! pidof -s pulseaudio >/dev/null 2>&1 &&
	setsid -f pulseaudio --start --exit-idle-time=-1 >/dev/null 2>&1
